// ng-todo/src/app/add-todo/add-todo.component.ts
import { Component, OnInit } from '@angular/core';
import AppService from '../app.service';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
})
export class AddTodoComponent implements OnInit {

  dataset: FormGroup;
  constructor(
    private appService: AppService,
  ) { }

  ngOnInit(): void {
    this.dataset = new FormGroup({
      content: new FormControl(null, Validators.required)
    });
  }

  addTodo = (): void => {
    this.appService.handleSubmit(this.dataset.value.content);
    this.dataset.reset();
  }
}

<form [formGroup]="dataset" (ngSubmit)="addTodo()" novalidate>
  <input formControlName="content" type="text" placeholder="add Todo">
  <button class="add" type="submit" [disabled]="dataset.invalid">
    add
  </button>
</form>

// v4/src/component/addTodo.tsx
import React, { Component } from 'react';

interface IProps {
    onChange: (text: string) => void;
    onSubmit: () => void;
}
export default class AddTodo extends Component<IProps> {
    
    handleSubmit = (e: any): void => {
        e.preventDefault();
        e.stopPropagation();
        this.props.onSubmit();
        e.target.reset();
    }

    render(): JSX.Element {
        return (
            <form onSubmit={(e) => this.handleSubmit(e)}>
                <input type="text" placeholder="add Todo" onChange={(e) => this.props.onChange(e.target.value)}/>
                <button className="add" type="submit">
                    add
                </button>
            </form>
        );
    }
}
